class Employee {
  int? employeeId; // This is auto-generated by the backend
  String firstName;
  String lastName;
  String designation;
  String department;
  double salary;
  String dateOfJoining;

  Employee({
    this.employeeId, // Nullable, since it will be generated by the backend
    required this.firstName,
    required this.lastName,
    required this.designation,
    required this.department,
    required this.salary,
    required this.dateOfJoining,
  });

  factory Employee.fromJson(Map<String, dynamic> json) {
    return Employee(
      employeeId: json['employeeId'], // The server will provide this
      firstName: json['firstName'],
      lastName: json['lastName'],
      designation: json['designation'],
      department: json['department'],
      salary: json['salary'],
      dateOfJoining: json['dateOfJoining'],
    );
  }

  Map<String, dynamic> toJson() {
    // Exclude employeeId here since the backend will generate it
    return {
      'employeeId': employeeId,
      'firstName': firstName,
      'lastName': lastName,
      'designation': designation,
      'department': department,
      'salary': salary,
      'dateOfJoining': dateOfJoining,
    };
  }
}
